Build kube-rbac-proxy binary during docker build
brancz/kube-rbac-proxy pull request #180
Opened 2022-07-04 12:29 UTC by knopt

This commit removes requirement of compiled binary being present in `_output` directory before calling `make container`. Effectively, `make build` step is no longer dependency of `make container` and `make container` can be executed at the same time for multiple platforms.

2022-07-05 14:56 UTC, knopt commented
cc @s-urbaniak

2022-08-03 08:30 UTC, ibihim commented
Sorry, we were in vacation mode 😄 I will take a look. From what I can see you are introducing multi-stage-builds, which is a best practice 👍

2022-08-04 10:23 UTC, ibihim approved these changes

2022-08-04 10:35 UTC, ibihim requested changes
Tests are failing.

2022-11-28 13:17 UTC, ibihim commented
I would close this issue as it is stale. Feel free to reopen it, once you work on it again.

2023-04-05 13:50 UTC, ibihim commented
I am closing the stale issue, but it would be nice to revisit that topic again.

2023-04-05 13:50 UTC, closed without merging